[build]
  publish = "."

[[redirects]]
  from = "/claim-submitted"
  to = "/submit-claim.html?submitted=true"
  status = 200

[[redirects]]
  from = "/track/*"  
  to = "/track-claims.html"
  status = 200

[[redirects]]
  from = "/support"
  to = "/contact.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"